pipeline:
  build:
    image: xtianw/ruby-node
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - RAILS_ENV=test

    commands:
      - gem install bundler --version 1.14.6 --conservative
      - bin/bundle install --jobs $(nproc) --without development production --path .bundle
      - bin/rake rubocop
      - bin/rake eslint:run
      - bin/rake scss_lint
      - bin/rake db:create
      - bin/rspec

  git_push:
    image: plugins/git-push
    branch: master
    remote: dokku@wtfismygearscore.com:wtfismygs
    force: false
    when:
      branch: master

cache:
  mount:
    - .bundle
    - .git

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
