build:
  image: xtianw/ruby-node
  environment:
    - CI=1
    - DATABASE_HOST=localhost
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=postgres
    - RAILS_ENV=test

  commands:
    - bin/bundle install --jobs $(nproc) --without development production --path .bundle
    - bin/rake rubocop
    - bin/rake eslint:run
    - bin/rake scss_lint
    - bin/rake db:create
    - bin/rspec

cache:
  mount:
    - .bundle
    - .git

compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

deploy:
  git_push:
    branch: master
    remote: dokku@wtfismygearscore.com:wtfismygs
    force: false
    when:
      branch: master
