require:
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-config-rufo: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "vendor/bundle/**/*"
    - Brewfile

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  IgnoredMethods:
    - configure
    - describe
    - feature
    - it
    - task

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 20

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Rails/HasManyOrHasOneDependent:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MessageExpectation:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true
