language: ruby
rvm:
  - 2.7

cache: bundler

addons:
  postgresql: "10"
  ssh_known_hosts: wtfismygearscore.com

env:
  - RAILS_ENV=test

before_install:
  - openssl aes-256-cbc -K $encrypted_815ab84354b0_key -iv $encrypted_815ab84354b0_iv -in .travis/deploy.key.enc -out .travis/deploy.key -d
  - gem install bundler
  - nvm install lts/*
  - nvm use lts/*

script:
  - bin/rake db:create
  - bin/test

deploy:
  provider: script
  script: bin/travis-deploy
  skip_cleanup: true
  on:
    branch: master
