language: ruby
rvm:
  - 2.7

bundler_args: "--jobs $(nproc)"
cache: bundler

addons:
  postgresql: "10"
  ssh_known_hosts: wtfismygearscore.com

env:
  - RAILS_ENV=test

script:
  - bin/rake db:create
  - bin/test

deploy:
  provider: script
  script: bin/travis-deploy
  on:
    branch: master
