language: ruby
rvm:
  - 2.7

cache: bundler

addons:
  postgresql: "10"
  ssh_known_hosts: wtfismygearscore.com

env:
  - RAILS_ENV=test

before_install:
  - gem install bundler

script:
  - bin/rake db:create
  - bin/test

deploy:
  provider: script
  script: bin/travis-deploy
  on:
    branch: master
