[package]
name = "wtfismygs"
version = "1.0.0"
authors = ["Christian Wesselhoeft <hi@xtian.us>"]
edition = "2018"
readme = "README.md"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
